### ISSUE TITLE
请教如何邀请入群及获取当前窗口的聊天对象信息？

### ISSUE THREAD

**Issue by binggandata** [JustUndertaker/adapter-ntchat#10]
你好，我打算实现关键词回复自动拉群的功能

目前写了一段测试代码如下，但是并没有反应，请问是哪里有问题吗？

此外，想请教一下，如何获取当前聊天窗口的聊天对象信息 wxid，这样我才能定向邀请对方入群

谢谢！

```python
matcher = on_command('/西南')

@matcher.handle()
async def invite_to_group_xinan(bot: Bot, event:TextMessageEvent):

    bot.invite_room_member(room_wxid='668818889@chatroom', member_list=['wxid_1181cbbx6vvc12'])
    logger.info('邀请好友进西南群')
```

附上运行的效果：

![64f6978851c2bbbc779cd2cfc1ed118](https://cdn.bggg.tech/md/64f6978851c2bbbc779cd2cfc1ed118.png)

**Comment by JustUndertaker** [comment]
建议你看看事件字段，里面都有注释
event.from_wxid  应该就是你要的

**Comment by binggandata** [comment]
> 建议你看看事件字段，里面都有注释 event.from_wxid 应该就是你要的

谢谢大佬，我再啃啃文档

那我上面那个 invite_room_member 邀请好友进群的语句有问题吗，没有反应，我看日志也没有说成功调用这个接口

**Comment by binggandata** [comment]
> > 建议你看看事件字段，里面都有注释 event.from_wxid 应该就是你要的
> 
> 谢谢大佬，我再啃啃文档
> 
> 那我上面那个 invite_room_member 邀请好友进群的语句有问题吗，没有反应，我看日志也没有说成功调用这个接口

```python
matcher = on_command('/西南')

@matcher.handle()
async def invite_to_group_xinan(bot: Bot, event:TextMessageEvent):

    context_wxid = event.from_wxid

    await bot.call_api("invite_room_member", room_wxid= '668818889@chatroom' , member_list=[context_wxid])
   
    logger.info('邀请好友进西南群')
```

更新一下，我用了call_api 的方法，后台显示调用成功，但实际上没有反应

**Comment by JustUndertaker** [comment]
这个客户端只是负责转发消息，传给ntchat那边，如果那边回复是成功而没有响应，可能是ntchat那边的问题。

**Comment by binggandata** [comment]
> 这个客户端只是负责转发消息，传给ntchat那边，如果那边回复是成功而没有响应，可能是ntchat那边的问题。

那是不是就无解了？求大佬指路

**Comment by binggandata** [comment]
反馈一下，今早测试了一下，在代码没改的情况下，又能拉人进群了。我发现几个群的room_wxid 变了，是会有这样的情况吗？
