### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by GabrielXie** [JustUndertaker/adapter-ntchat#11]
大佬，目前这个项目上游的逆向工程闭源了，虽然目前没有问题，但也要考虑以后版本更新的问题。
https://github.com/lich0821/WeChatFerry
看到这个项目还不错，相关的技术开发群也在着手更新一些功能。
所以想在咱们这个项目的基础上，Fock一份代码出来，做WeChatFerry的适配器，或者我直接提交新代码到这个项目的新分支上，再或者就是大佬你来开发。大佬意下如何

**Comment by JustUndertaker** [comment]
可以我先看看哈

**Comment by JustUndertaker** [comment]
新的repo正在开发中：
https://github.com/JustUndertaker/ComWeChatBotClient
重写一遍没什么意思，所以这次打算支持onebot12

**Comment by GabrielXie** [comment]
很赞哦，这个ComWeChatRobot看起来不错，我试试看
