### ISSUE TITLE
命令模式下，如何处理不同类型的消息

### ISSUE THREAD

**Issue by GabrielXie** [JustUndertaker/adapter-ntchat#6]
如我要接收命令，/test， 然后接收一条微信合并消息，由于文本和合并消息是不同类型（text、app）那么如何处理这种情况呢？

**Comment by GabrielXie** [comment]
正常的交互逻辑是：
user: /test
bot: 请发送聊天记录
user: 【合并聊天记录】
bot: 收到


但是由于输入两种不同类型，这个需求好像实现不了

**Comment by JustUndertaker** [comment]
消息能用同一个matcher捕获到就可以，使用matcher.got进行逻辑交互

**Comment by GabrielXie** [comment]
不同类型的好像不能用同一个matcher捕获，感觉应该无解了

**Comment by JustUndertaker** [comment]
也不是无解，你可以自己建立流程，新建临时的matcher

**Comment by GabrielXie** [comment]
好的，我尝试一下
