### ISSUE TITLE
无法发图片 send_image

### ISSUE THREAD

**Issue by binggandata** [JustUndertaker/adapter-ntchat#7]
这是我plugin 的代码

设置了定时发送，但是时间一到，可以正常下载图片，client也说正常运行，正常调用send_image接口，状态200，但在微信界面没有发出图片，换了很多形式都不行。同样的代码，在朋友电脑上运行是正常可以发图的。

另外，我是部署在了腾讯云服务器 windows server 上 ，平时可以正常发文字，图片发不了，可以帮我看看为什么吗？

```python
from nonebot import require, get_bot
from nonebot.adapters.ntchat import Bot, MessageSegment ,PictureMessageEvent
from nonebot.plugin import on_message
import requests
# from PIL import Image
from datetime import datetime
import os
from pathlib import Path


scheduler = require("nonebot_plugin_apscheduler").scheduler

@scheduler.scheduled_job("cron", day_of_week='*', hour='10', minute='9', second='30' )
async def get_news():

    today = datetime.strftime(datetime.today().date(),'%Y-%m-%d')

    r = requests.get('https://api.vvhan.com/api/60s')

    path = os.path.abspath(os.path.dirname(__file__))
    print(path)
    # image_path = 'C:\\Users\\Administrator\\Desktop\\nonebot-wechat\\wxbot_nt\\plugins\\day_tasks\\data\\'+today+'.jpg'
    image_path = './image/'+today+'.png'

    with open(image_path, 'wb') as f:
        f.write(r.content)
        f.close()

    bot= get_bot()

    # receivers = ['34559154688@chatroom','21308696088@chatroom','19428044546@chatroom','18004449763@chatroom','sonnyle']
    receivers = ['sonnyle', '34379663133@chatroom']


    for receiver in receivers:
        await bot.send_image(to_wxid = receiver, file_path=Path(image_path))
        # await bot.send_image(to_wxid = receiver, file_path='https://api.vvhan.com/api/60s')

    print('完成日报发送')
```

**Comment by JustUndertaker** [comment]
具体原因不清楚，但是就你的代码来说，还是得换个形式，这段代码同步阻塞太严重，建议改为异步。
同时send_image支持url图片，你可以直接把url发过去就可以。

**Comment by wuchangjun233** [comment]
你可以尝试使用base64编码方式发送，或者在发送前读取为bytes

**Comment by binggandata** [comment]
> 具体原因不清楚，但是就你的代码来说，还是得换个形式，这段代码同步阻塞太严重，建议改为异步。 同时send_image支持url图片，你可以直接把url发过去就可以。

谢谢回复，但是我删掉request部分的内容，仅用url也不行，但是下面兄弟说改成bytes的形式就可以了

**Comment by binggandata** [comment]
> 你可以尝试使用base64编码方式发送，或者在发送前读取为bytes

谢谢回复，读取为bytes就可以发出去了。

**Comment by GabrielXie** [comment]
> 

先重定向获取新的地址就可以了
```python
import requests

            response = requests.get(url=yourURL)
            await bot.send_image(to_wxid=r, file_path=response.url)

```

**Comment by GabrielXie** [comment]
> 你可以尝试使用base64编码方式发送，或者在发送前读取为bytes

先重定向获取新的地址就可以了

import requests

            response = requests.get(url=yourURL)
            await bot.send_image(to_wxid=r, file_path=response.url)

**Comment by GabrielXie** [comment]
> > 具体原因不清楚，但是就你的代码来说，还是得换个形式，这段代码同步阻塞太严重，建议改为异步。 同时send_image支持url图片，你可以直接把url发过去就可以。
> 
> 谢谢回复，但是我删掉request部分的内容，仅用url也不行，但是下面兄弟说改成bytes的形式就可以了

先重定向获取新的地址就可以了

import requests

            response = requests.get(url=yourURL)
            await bot.send_image(to_wxid=r, file_path=response.url)

**Comment by GabrielXie** [comment]
> > 具体原因不清楚，但是就你的代码来说，还是得换个形式，这段代码同步阻塞太严重，建议改为异步。 同时send_image支持url图片，你可以直接把url发过去就可以。
> 
> 谢谢回复，但是我删掉request部分的内容，仅用url也不行，但是下面兄弟说改成bytes的形式就可以了

先重定向获取新的地址就可以了

```python
import requests

response = requests.get(url=yourURL)
await bot.send_image(to_wxid=r, file_path=response.url)
```

**Comment by binggandata** [comment]
> > > 具体原因不清楚，但是就你的代码来说，还是得换个形式，这段代码同步阻塞太严重，建议改为异步。 同时send_image支持url图片，你可以直接把url发过去就可以。
> > 
> > 
> > 谢谢回复，但是我删掉request部分的内容，仅用url也不行，但是下面兄弟说改成bytes的形式就可以了
> 
> 先重定向获取新的地址就可以了
> 
> ```python
> import requests
> 
> response = requests.get(url=yourURL)
> await bot.send_image(to_wxid=r, file_path=response.url)
> ```

谢谢大佬，学习了
